### ISSUE TITLE
ProxyAdmin deployment failed for testing 0.9.5 upgrade

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-core#205]
```
Using initial contracts file:  initial-contracts.json
Preparing contract:  ValidatorSetHbbft
Preparing contract:  BlockRewardHbbft
Preparing contract:  RandomHbbft
Preparing contract:  TxPermissionHbbft
Preparing contract:  CertifierHbbft
Preparing contract:  KeyGenHistory
Preparing contract:  StakingHbbft
compiling admin contract. owner:  0x32c5f14302d4Dd973e0040a5d7Eda97222A928D1
An unexpected error occurred:

Error: too many arguments:  in Contract constructor (count=1, expectedCount=0, code=UNEXPECTED_ARGUMENT, version=contracts/5.7.0)
    at Logger.makeError (/root/tests/diamond-contracts-core/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/root/tests/diamond-contracts-core/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.checkArgumentCount (/root/tests/diamond-contracts-core/node_modules/@ethersproject/logger/src.ts/index.ts:347:18)
    at ContractFactory.getDeployTransaction (/root/tests/diamond-contracts-core/node_modules/@ethersproject/contracts/src.ts/index.ts:1216:16)
    at SpecialContract.<anonymous> (/root/tests/diamond-contracts-core/tasks/types.ts:155:28)
    at Generator.next (<anonymous>)
    at fulfilled (/root/tests/diamond-contracts-core/tasks/types.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'too many arguments:  in Contract constructor',
  code: 'UNEXPECTED_ARGUMENT',
  count: 1,
  expectedCount: 0
}
```
but the Admin contract takes exactly 1 argument.

**Comment by SurfingNerd** [comment]
we upgrade to OpenZeppelin 5
